version: 4.7.{build}-rgl
skip_tags: true
image: Visual Studio 2017
shallow_clone: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: A5Y5pKzc8Xf2qOCrFqYP2BWQYKif/BtlesWT/uojWfOFJj5jcSOaHP+DfwVYid09
  COVERITY_TOKEN:
    secure: q4yqC+X51LwoyuBcg0qvks1117rt1HwqsDErKsbLpsQ=
  COVERITY_EMAIL:
    secure: lgy4M/uQ9jMlxmPzTIYWVE2GggvPntq6kfpO6Z0pjAs=
  SONARQUBE_TOKEN:
    secure: WRLqxS8frIuLNHeSMOj6SXvR3S0gx3RM0bgGkWeglXMIPSVS/VNmfUEqdHYZ2QOB
  DRDUMP_TOKEN:
    secure: 16PEs46poxfT7drt6BdHSHPPzAymXBYrIaqoAsHvY49os5Azz4rNTp3QaUhtITZ+
cache:
- build/Version/opencover.snk
- build/Version/opencover.public.snk
nuget:
  disable_publish_on_pr: true
install:
- ps: >-
    Write-Host 'Downloading Microsoft .NET Framework 4.7.1 Developer Pack...'
    
    $exePath = "$($env:USERPROFILE)\VSIsoShell.exe"
    
    (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/9/0/1/901B684B-659E-4CBD-BEC8-B3F06967C2E7/NDP471-DevPack-ENU.exe', $exePath)
    
    Write-Host 'Installing Microsoft .NET Framework 4.7.1 Developer Pack...'
    
    cmd /c start /wait "$exePath" /q /norestart
    
    Write-Host 'Downloading Installing vera++1.3.0-win32...'
    
    $exePath = "$($env:USERPROFILE)\vera++-1.3.0-win32.exe"
    
    (New-Object Net.WebClient).DownloadFile('https://bitbucket.org/verateam/vera/downloads/vera++-1.3.0-win32.exe', $exePath)
    
    Write-Host 'Installing vera++1.3.0-win32...'
    
    cmd /c start /wait "$exePath" /S
    
before_build:
- ps: >-
    #do nothing
build_script:
- ps: >-
    if ($env:APPVEYOR_SCHEDULED_BUILD -eq "True" -or $env:APPVEYOR_REPO_BRANCH -eq "coverity") {
      & .\build.bat create-coverity-release
    } else {
      & .\build.bat create-release
    }
        
    if ($LastExitCode -ne 0) {
        throw "build.bat failed with exit code $LastExitCode."
    }    
test: off
artifacts:
- path: main/bin/installer/*.msi
  name: Installer
- path: main/bin/zip/*.zip
  name: ZipArchive
- path: main/bin/packages/nuget/opencover/*.nupkg
  name: Nuget
- path: main/bin/packages/nuget/opencover-rc/*.nupkg
  name: NugetCandidate
- path: main/bin/packages/chocolatey/opencover/*.nupkg
  name: Chocolatey
- path: main/bin/packages/chocolatey/opencover.portable/*.nupkg
  name: ChocolateyPortable
- path: cov-int/build-log.txt
  name: Coverity
- path: GenericCoverage.xml
  name: cpp-coverage
- path: main/bin/release/opencovertests.xml
  name: cs-coverage
